user nginx;

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # Dockerログへ出力
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    # gzip
    gzip on;
    gzip_types
        text/plain
        text/css
        application/javascript
        application/json;
    include /etc/nginx/conf.d/*.conf;

}